groundstation:
  name: 'DK0TU Groundstation'
  location: '52.5122, 13.3270'  # GPS Coordinates or Address of the Groundstation
  rotator:
    type: 'spid'  # Currently, only 'spid' type are supported
    netrotctl_ip: 'localhost'  # IP address of the netrotctl server
    netrotctl_port: '4533'  # Port of the netrotctl server
  sdr:
    type: 'uhd'  # Currently, 'uhd', 'lime' and 'rtlsdr' SDRs are supported
    sample_rate: 4e6  # Value in [Hz], if no sample rate is provided -> fallback to <type> default
    lna_gain: 76  # Value in [dB], if no lna gain is provided -> fallback to <type> default
  antenna:
    name: 'L+S-Band Dish'
    type: 'parabolic'  # Currently 'parabolic' and 'generic' type antennas are supported
    gain: 4.75  # Value in [dBi], if parabolic antenna -> only the gain of feed, gain of dish will be calc. via diameter
    opening_azimuth:  # Value in [deg], if parabolic antenna -> will be calculated via dish diameter
    opening_elevation:  # Value in [deg], if parabolic antenna -> will be calculated via dish diameter
    diameter: 3.0  # Value in [m]
    frequency_range: [1200e6, 1300e6]  # [2320e6, 2450e6]
  webcam:
    rtsp_url: 'rtsp://admin:430,200@localhost:1554/h264Preview_01_main'
    cam_opening: 90  # Horizontal opening angle of webcam in [deg]
    position_azimuth: 0.539 # 0.5742  # Position of pointing direction of antenna in azimuth axis in percent of image width
    position_elevation: 0.5625  # Position of pointing direction of antenna in elevation axis in percent of image height
controller:
  application_port: 8050  # Port of the web application which will show the results
  target_object: "Sun"  # Name of the astronomical object which shall be tracked e.g. sun, moon, sagittarius a*, ...
  target_frequency: 1250e6
  step_size_azimuth: 1
  step_size_elevation: 1
  scan_width_azimuth: 10
  scan_width_elevation: 10